### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by pmhoppe** [zacharee/BoredSigns#3]
How about a text notification flashing icon. I really miss the colored led from my old phone.

**Comment by zacharee** [comment]
I can make a widget that flashes a chosen color when a notification comes in, but it would only be useful when the screen is on. You can't have an AOD widget stay on-screen always, since LG forces the AOD back to the time/signature screen after a few seconds. The widget also wouldn't update properly in the AOD, so it wouldn't flash.
