### ISSUE TITLE
Suggestion: GIF

### ISSUE THREAD

**Issue by Migushthe2nd** [zacharee/BoredSigns#4]
Being able to select a gif to use on the image screen would be amazing

**Comment by Migushthe2nd** [comment]
Also a button you can assign a sound effect to. These are just suggestions.

**Comment by Migushthe2nd** [comment]
Also a button to assign a sound file to. These are just suggestions.

**Comment by vMarxx** [comment]
The gif image would be amazing, i just bought the application also I want to contribute to do that

**Comment by zacharee** [comment]
I've already said, it's impossible.


On 9 abr. 2018 at 3:37 PM, <vMarxx <notifications@github.com>> wrote:

The gif image would be amazing, i just bought the application also I want
to contribute to do that

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/BoredSigns/issues/4#issuecomment-379869136>,
or mute the thread

**Comment by vMarxx** [comment]
Oh i didnt see, the thing is that i have seen this animation on a LG v10 video (https://youtu.be/Vg3OM56aNYA) and i suppose that maybe is possible to set one. Thanks for your reply.

**Comment by zacharee** [comment]
That's on Marshmallow or Lollipop, which used a completely different
framework. You can't even add third party widgets to it.


On 10 abr. 2018 at 12:21 PM, <vMarxx <notifications@github.com>> wrote:

Oh i didnt see, the thing is that i have seen this animation on a LG v10
video (https://youtu.be/Vg3OM56aNYA) and i suppose that maybe is possible
to set one. Thanks for your reply.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/BoredSigns/issues/4#issuecomment-380162004>,
or mute the thread
